version: "2"
services:
  lwns-api-go:
    build:
      context: .
      dockerfile: Dockerfile-go
    command: bash -c "cd go && make all"
    volumes:
      - ./:/lwns-api
  lwns-api-swagger:
    build:
      context: .
      dockerfile: Dockerfile-go
    command: bash -c "cd swagger && make all"
    volumes:
      - ./:/lwns-api
  
